### ISSUE TITLE
Selectable icons do not appear in IE

### ISSUE THREAD

**Issue by zrouse** [OpenCOP/OpenCOP#16]
Reproduce on IE:
demo/opencop- add La_Bio:LSU_birds
select that layer and go to edit tab
no bird icon shows in tab

**Comment by ghost** [comment]
Oh buddy.  Let the IE bugs begin!

**Comment by zrouse** [comment]
I know we have seen worse.  Brandon got a usable error msg out of IE: (UPDATE: LINE #'s MIGHT HAVE CHANGED A BIT)
Message: Object doesn't support this property or method
Line: 940
Char: 13
Code: 0
URI: http://demo.geocent.com/opencop/main.js

Message: 'dom.style' is null or not an object
Line: 7
Char: 34135
Code: 0
URI: http://demo.geocent.com/opencop/lib/ext-3.4.0/ext-all.js
