### ISSUE TITLE
Add layer popup has more tabs than it can handle

### ISSUE THREAD

**Issue by zrouse** [OpenCOP/OpenCOP#18]
demo/opencop add layers

http://examples.extjs.eu/    ->Examples->layout->dynamic tab has some scroll buttons when you add more tabs than can fit.
Maybe an option somewhere

**Comment by ghost** [comment]
I added `enableTabScroll:true` to all the tabpanels I could find.  Silly that that's not the default setting.

**Comment by zrouse** [comment]
Oh happy day, that was an annoying one.  Good find!
