### ISSUE TITLE
cusor keeps the circle-plus

### ISSUE THREAD

**Issue by jameshaynie** [OpenCOP/OpenCOP#21]
1. Edit mode (get the plus to add)
2. Change Base Layer
3. Plus sign remains
4. Change Edit tab to Details tab (plus remains)
5. Change Layer (plus remains)
6. Close out browser
7. Open browser
8. Everything works again

**Comment by thanthese** [comment]
Closed 30Mar2012.  Problem was that I forgot to deactivate drawControl in the refreshControls function.
