### ISSUE TITLE
Add link back to geoserver as settings button

### ISSUE THREAD

**Issue by OpenCOP** [OpenCOP/OpenCOP#27]
Perhaps link back to a layer preview like page that shows the opencop namespaced layers and a link to the wfs-t page for each.

**Comment by ghost** [comment]
I added back the Application Settings button.  Right now it points to GeoServer homepage.

**Comment by ghost** [comment]
I'm gonna close this issue.  If we want an "opencop admin" page in GeoServer, we should create a new issue in the extensions repository.
