### ISSUE TITLE
WMS Getfeatureinfo popup InfoFormat change

### ISSUE THREAD

**Issue by OpenCOP** [OpenCOP/OpenCOP#29]
need to support text/html
maybe this helps:
http://trac.geoext.org/browser/sandbox/fvanderbiest/openlayers/examples/getfeatureinfo.html

Test is the NEPLO box readiness layer looking pretty

**Comment by zrouse** [comment]
I fear that example is pure openlayers

**Comment by ghost** [comment]
Committed the change for this.  Still need to figure out how to prevent the popup if there is an empty response.
