### ISSUE TITLE
Sometimes it caches wms requests

### ISSUE THREAD

**Issue by zrouse** [OpenCOP/OpenCOP#33]
placeholder for issue
This makes for bad real time action

**Comment by ghost** [comment]
I think I have a solution for this, it's gonna be hard to test.  I'm having trouble reproducing it.

**Comment by thanthese** [comment]
Closed: 6fb6de02c7d2fe4f4e6a8dff92e39a9dea14160d, wasn't able to reproduce.

These were the steps I remember Paul taking when he saw the issue.
- Zoom in on `tracker` on [dev](http://geo-dev.geocent.com/opencop) real close, one level at a time.
- Delete a line feature.
- Zoom out one level, and the deleted feature stills shows up (cached).

Maybe this commit cc7e083656805e88f6a2bbcaeccdba96d826ee82 fixed it?

I did implement Yancy's theory, just to be sure.  (See commit for details.)
