### ISSUE TITLE
wms layers don't match base layer when you use zoom bar

### ISSUE THREAD

**Issue by zrouse** [OpenCOP/OpenCOP#34]
sometimes

**Comment by zrouse** [comment]
can't ignore this anymore

**Comment by ghost** [comment]
I think this is a bug in GeoExt.  We aren't doing anything crazy with it.

**Comment by zrouse** [comment]
Also seen with mouse wheel.  OpenLayers?  Windows/firefox

**Comment by thanthese** [comment]
Fixed.  See commit msg: cc7e083656805e88f6a2bbcaeccdba96d826ee82
