### ISSUE TITLE
opacity slider is goofy

### ISSUE THREAD

**Issue by zrouse** [OpenCOP/OpenCOP#35]
more to come

**Comment by zrouse** [comment]
recipe on demo:
add bear sightings
activate bear sightings layer
->opacity slider starts not at 100%
activate base layer
manipulate opacity slider
->it gets jittery
select new base layer
return to original base layer
->better

**Comment by thanthese** [comment]
"fixed" by disabling opacity slider for base layers.  I think a more real fix would include rolling our own slider.
