### ISSUE TITLE
Hello world Selenium

### ISSUE THREAD

**Issue by zrouse** [OpenCOP/OpenCOP#38]

**Comment by slimbolala** [comment]
Created a new (Eclipse-flavored) Selenium 2.0 + Java project in the new selenium_tests directory under the project's root. Currently has a single JUnit4/Selenium WebDriver TestCase with a single test method, testOpenCopExists() which loads OpenCOP and asserts a title of "OpenCOP 2.0". Test infrastructure in place. Now for some _real_ testing fun!
