### ISSUE TITLE
Bug: error zooming in too close with google physical

### ISSUE THREAD

**Issue by thanthese** [OpenCOP/OpenCOP#46]
## Steps to reproduce
- [dev](http://ge-dev.geocent.com/opencop)
- select the `tracker` layer
- select the `Google Physical` base layer
- using the widget, zoom in on `tracker`, as close as you can
## The bug

`tracker` will keep getting bigger, but `Google Physical` will stop zooming in at some point.  At that point the two zoom levels will be out of sync.
## Musings

This only seems to happen with `Google Physical`.  It does _not_ happen with `Google Streets`, even though they have the same `numzoomlevels` in the database.

I think `Google Physical` doesn't support zooming in beyond some point, and it's not failing gracefully.  If that's the case, I'm not sure how to restrict zooming based on the current base layer (or even how we find out what to restrict it to).

**Comment by thanthese** [comment]
Removing all refs to `numzoomlevels` from the code doesn't help.  OpenLayers and Google don't seem to automatically "do the right thing".

**Comment by slimbolala** [comment]
Dang, base layers are getting _narsty_. Worst case: we can manually determine max zoom level of Physical (and double-check others) and, if need be, add explicit logic to prevent excess zooming when Physical is selected. And then wrap it all up in some sort of way that the heinousness is appropriately hidden from the rest of the code.
