### ISSUE TITLE
db-setups for icons only register 2525b icons

### ISSUE THREAD

**Issue by zrouse** [OpenCOP/OpenCOP#49]
Opencop-icons has the standard HSWG icons and those need to be published.

**Comment by thanthese** [comment]
commit 4e1544e3340aca35baab0b14b55cc123d9ae4fc8 closed this

**Comment by thanthese** [comment]
The icons have been added to the [binaries](https://github.com/OpenCOP/binaries/commit/c549695af38aa82c7a516946a1f373af34173766) repo.
