### ISSUE TITLE
Inconsistency: close all popups by clicking off

### ISSUE THREAD

**Issue by thanthese** [OpenCOP/OpenCOP#52]
Some popups can be closed by clicking anywhere that isn't a popup, and some can't.  Specifically, WMS Get Feature Info can't.  Make this consistent.

**Comment by zrouse** [comment]
N.B. WFS edit popups won't be able to comply with this because we allow moving of points.

**Comment by thanthese** [comment]
In fact, they already do because we can make a distinction between clicking
and dragging.

On Wed, Apr 11, 2012 at 10:45 AM, Zach <
reply@reply.github.com

**Comment by zrouse** [comment]
Ha!  Awesome
