### ISSUE TITLE
bug: can't edit line geometries

### ISSUE THREAD

**Issue by thanthese** [OpenCOP/OpenCOP#69]
Maybe not so much as a bug as an as-of-yet unimplemented feature, but you can't edit a line's points after creation.

**Comment by ghost** [comment]
Polygons didn't work either.  Did you fix that?

**Comment by thanthese** [comment]
Sadly, apparently not.  Polygons have even more parents than lines.  And
multi-polygons even more than that.  It looks like `
geometry.parent.parent.parent.parent.id`.  I'll fix it tomorrow.

On Wed, Apr 18, 2012 at 12:19 PM, Yancy Matherne <
reply@reply.github.com

**Comment by thanthese** [comment]
Closed issue again.  Now you can edit polygons.
